# Generated by Django 6.0.3 on 2026-04-04 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SousService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "service_parent",
                    models.CharField(
                        choices=[("OSN", "OSN"), ("OBT", "OBT")], max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdreTravail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("reference_externe", models.CharField(blank=True, max_length=50)),
                ("objet", models.CharField(blank=True, max_length=255)),
                ("lieu", models.CharField(blank=True, max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_debut", models.DateTimeField(blank=True, null=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("date_archivage", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                (
                    "statut_validation",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "client_rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordres_travail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ot_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentOT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("pv", "Procès-verbal"),
                            ("bl", "Bon de livraison"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fichier", models.FileField(upload_to="ot_documents/")),
                ("nom", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.ordretravail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapportHebdoCadre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("av", "Avant-Vente"),
                            ("projets", "Projets"),
                            ("maintenances", "Maintenances / Interventions"),
                            ("autres", "Autres"),
                        ],
                        default="maintenances",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cadre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_hebdo_cadre",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneRapportHebdoCadre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nature_intervention", models.CharField(max_length=255)),
                ("avancement_resultat", models.TextField()),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("numero_ticket", models.CharField(blank=True, max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
                (
                    "intervenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_hebdo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="api.rapporthebdocadre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapportJournalier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_journaliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("technicien", "date")},
            },
        ),
        migrations.CreateModel(
            name="LigneRapportJournalier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nature_intervention",
                    models.CharField(
                        max_length=255, verbose_name="Nature de l'intervention"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description du travail effectué"),
                ),
                (
                    "avancement_resultat",
                    models.TextField(blank=True, verbose_name="Avancement / Résultat"),
                ),
                (
                    "date_debut",
                    models.TimeField(blank=True, null=True, verbose_name="Heure début"),
                ),
                (
                    "date_fin",
                    models.TimeField(blank=True, null=True, verbose_name="Heure fin"),
                ),
                (
                    "duree",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Durée (heures)"
                    ),
                ),
                (
                    "numero_ticket",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="N° Ticket"
                    ),
                ),
                (
                    "rit_signe",
                    models.BooleanField(default=False, verbose_name="RIT signé"),
                ),
                (
                    "pv_signe",
                    models.BooleanField(default=False, verbose_name="PV signé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
                (
                    "ot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ordretravail",
                    ),
                ),
                (
                    "rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="api.rapportjournalier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de rapport journalier",
                "verbose_name_plural": "Lignes de rapports journaliers",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "sous_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.sousservice",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuiviOT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heures", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivis",
                        to="api.ordretravail",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivis_ot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("ot", "technicien", "date")},
            },
        ),
    ]
