# Generated by Django 6.0.3 on 2026-04-05 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordretravail",
            name="estimation_heures",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimation en heures",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordretravail",
            name="parent_ot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sous_ots",
                to="api.ordretravail",
            ),
        ),
        migrations.AddField(
            model_name="ordretravail",
            name="techniciens",
            field=models.ManyToManyField(
                blank=True, related_name="ordres_travail", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="ordretravail",
            name="technicien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordres_travail_anciens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
