# Generated by Django 6.0.1 on 2026-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommande",
            name="devise",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro (€)"),
                    ("USD", "Dollar ($)"),
                    ("GBP", "Livre sterling (£)"),
                    ("XAF", "Franc CFA (FCFA)"),
                    ("MAD", "Dirham marocain (MAD)"),
                    ("DZD", "Dinar algérien (DA)"),
                    ("TND", "Dinar tunisien (DT)"),
                    ("AED", "Dirham émirati (AED)"),
                    ("CNY", "Yuan chinois (CNY)"),
                    ("JPY", "Yen japonais (¥)"),
                ],
                default="EUR",
                max_length=3,
            ),
        ),
    ]
