# Generated by Django 6.0.3 on 2026-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_ordretravail_estimation_heures_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordretravail",
            name="reference",
            field=models.CharField(
                help_text="Numéro OT (saisie manuelle)", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ordretravail",
            name="reference_externe",
            field=models.CharField(
                blank=True, help_text="Référence bon de commande client", max_length=50
            ),
        ),
    ]
