# Generated by Django 6.0.1 on 2026-03-04 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_bondecommande_devise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportHebdomadaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("activites", models.TextField()),
                ("objectifs_atteints", models.TextField()),
                ("difficultes", models.TextField()),
                ("propositions", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cadre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_hebdomadaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapportJournalier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("heure_depart", models.TimeField()),
                ("heure_arrivee", models.TimeField()),
                ("heure_rdv", models.TimeField()),
                ("type_intervention", models.CharField(max_length=100)),
                ("rdv_planifie", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("rit_signe", models.BooleanField(default=False)),
                ("pv_signe", models.BooleanField(default=False)),
                ("conclusions", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_journaliers",
                        to="api.missionv2",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_journaliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapportProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projet", models.CharField(max_length=200)),
                ("date", models.DateField(auto_now_add=True)),
                ("avancement", models.IntegerField(help_text="Pourcentage réalisé")),
                ("taches_realisees", models.TextField()),
                ("prochaines_taches", models.TextField()),
                ("remarques", models.TextField(blank=True)),
                (
                    "ingenieur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_projet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
