# Generated by Django 6.0.3 on 2026-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_ordretravail_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentot",
            name="type",
            field=models.CharField(
                choices=[
                    ("photo", "Photo (travail effectué)"),
                    ("screenshot", "Capture écran / Email"),
                    ("pdf", "PDF reçu / Document"),
                    ("cr", "Compte rendu de réunion"),
                    ("autre", "Autre"),
                ],
                max_length=20,
            ),
        ),
    ]
