# Generated by Django 6.0.1 on 2026-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rapporthebdomadaire_rapportjournalier_rapportprojet"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuiviMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("service", models.CharField(max_length=100)),
                ("date_delivrance", models.DateField()),
                ("date_expiration", models.DateField()),
                ("type_certificat", models.CharField(blank=True, max_length=100)),
                ("clinique", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
