# Generated by Django 6.0.1 on 2026-03-10 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_suivimedical"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdreTravail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_debut", models.DateTimeField(blank=True, null=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                ("intervenants", models.CharField(blank=True, max_length=255)),
                ("date_intervention", models.DateField(blank=True, null=True)),
                ("heure_depart_nasa", models.TimeField(blank=True, null=True)),
                ("heure_arrivee_client", models.TimeField(blank=True, null=True)),
                ("heure_rdv_client", models.TimeField(blank=True, null=True)),
                ("type_intervention", models.CharField(blank=True, max_length=100)),
                ("rdv_planifie", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("rit_signe", models.BooleanField(default=False)),
                ("pv_signe", models.BooleanField(default=False)),
                ("conclusions", models.TextField(blank=True)),
                (
                    "bon_commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordres_travail",
                        to="api.bondecommande",
                    ),
                ),
                (
                    "client_rapport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.client",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordres_travail",
                        to="api.missionv2",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordres_travail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
