# Generated by Django 6.0.3 on 2026-04-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_projet_heureprojet"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapportjournalier",
            name="sous_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.sousservice",
            ),
        ),
    ]
