# Generated by Django 6.0.1 on 2026-03-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_ordretravail"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordretravail",
            name="code_client",
            field=models.CharField(
                blank=True, help_text="Code client (BP code)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="ordretravail",
            name="reference_externe",
            field=models.CharField(
                blank=True, help_text="Référence SAGE", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="ordretravail",
            name="statut_validation",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("valide", "Validé"),
                    ("rejete", "Rejeté"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DocumentOT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("pv", "Procès-verbal"),
                            ("bl", "Bon de livraison"),
                            ("qualite", "Fiche qualité"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fichier", models.FileField(upload_to="ot_documents/")),
                ("nom", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.ordretravail",
                    ),
                ),
            ],
        ),
    ]
