# Generated by Django 6.0.3 on 2026-04-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rapportjournalier_sous_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lignerapportjournalier",
            options={"ordering": ["date_debut"]},
        ),
        migrations.AddField(
            model_name="rapporthebdocadre",
            name="actions_notables",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rapporthebdocadre",
            name="difficultes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rapporthebdocadre",
            name="heures_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="rapporthebdocadre",
            name="nb_interventions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rapporthebdocadre",
            name="perspectives",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rapporthebdocadre",
            name="resume",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="avancement_resultat",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="date_debut",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="date_fin",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="duree",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="nature_intervention",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="numero_ticket",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="pv_signe",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lignerapportjournalier",
            name="rit_signe",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ordretravail",
            name="estimation_heures",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="estimation_heures",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.DeleteModel(
            name="LigneRapportHebdoCadre",
        ),
    ]
