# Generated by Django 6.0.3 on 2026-04-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_lignerapportjournalier_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rapportjournalier",
            name="sous_service",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="sous_service",
        ),
        migrations.AddField(
            model_name="technician",
            name="sous_services",
            field=models.ManyToManyField(
                blank=True, related_name="techniciens", to="api.sousservice"
            ),
        ),
    ]
