# Generated by Django 6.0.1 on 2026-03-11 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_ordretravail_code_client_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordretravail",
            name="date_validation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordretravail",
            name="reference_bc_externe",
            field=models.CharField(
                blank=True, help_text="Référence bon de commande externe", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="ordretravail",
            name="reference_devis",
            field=models.CharField(
                blank=True, help_text="Référence devis", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="ordretravail",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ot_valides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ordretravail",
            name="reference_externe",
            field=models.CharField(
                blank=True, help_text="Référence SAGE (OT)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="ordretravail",
            name="statut_validation",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente de validation"),
                    ("valide", "Validé"),
                    ("rejete", "Rejeté"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
