# Generated by Django 6.0.3 on 2026-04-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_rapportjournalier_sous_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapporthebdocadre",
            name="sous_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.sousservice",
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="sous_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.sousservice",
            ),
        ),
    ]
