# Generated by Django 6.0.1 on 2026-03-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_ordretravail_date_validation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordretravail",
            name="date_archivage",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
