# Generated by Django 6.0.3 on 2026-04-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_rapporthebdocadre_sous_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="benefice_attendu",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Bénéfice attendu en FCFA",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="cout_projet",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Coût total du projet en FCFA",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapporthebdocadre",
            name="tickets",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
