# Generated by Django 6.0.1 on 2026-03-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_rapportjournalier_mission_planninghebdomadaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordretravail",
            name="objet",
            field=models.CharField(
                blank=True,
                help_text="Objet de l'intervention (saisie libre)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="ordretravail",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordres_travail",
                to="api.missionv2",
            ),
        ),
    ]
