# Generated by Django 6.0.3 on 2026-04-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_projet_benefice_attendu_projet_cout_projet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="devise_benefice",
            field=models.CharField(
                choices=[
                    ("XAF", "Franc CFA (CEMAC) - XAF"),
                    ("XOF", "Franc CFA (UEMOA) - XOF"),
                    ("ZAR", "Rand - ZAR (Afrique du Sud)"),
                    ("MAD", "Dirham - MAD (Maroc)"),
                    ("EGP", "Livre - EGP (Égypte)"),
                    ("NGN", "Naira - NGN (Nigéria)"),
                    ("EUR", "Euro - EUR"),
                    ("GBP", "Livre Sterling - GBP"),
                    ("CHF", "Franc Suisse - CHF"),
                    ("USD", "Dollar US - USD"),
                    ("CAD", "Dollar Canadien - CAD"),
                    ("BRL", "Real - BRL (Brésil)"),
                    ("MXN", "Peso - MXN (Mexique)"),
                    ("JPY", "Yen - JPY (Japon)"),
                    ("CNY", "Yuan - CNY (Chine)"),
                    ("INR", "Roupie - INR (Inde)"),
                    ("KRW", "Won - KRW (Corée du Sud)"),
                    ("THB", "Baht - THB (Thaïlande)"),
                    ("SGD", "Dollar - SGD (Singapour)"),
                    ("MYR", "Ringgit - MYR (Malaisie)"),
                    ("IDR", "Roupie - IDR (Indonésie)"),
                    ("PHP", "Peso - PHP (Philippines)"),
                    ("VND", "Dong - VND (Vietnam)"),
                    ("AED", "Dirham - AED (EAU)"),
                    ("SAR", "Riyal - SAR (Arabie Saoudite)"),
                    ("QAR", "Riyal - QAR (Qatar)"),
                    ("KWD", "Dinar - KWD (Koweït)"),
                    ("BHD", "Dinar - BHD (Bahreïn)"),
                    ("AUD", "Dollar Australien - AUD"),
                    ("NZD", "Dollar Néo-Zélandais - NZD"),
                ],
                default="XAF",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="devise_cout",
            field=models.CharField(
                choices=[
                    ("XAF", "Franc CFA (CEMAC) - XAF"),
                    ("XOF", "Franc CFA (UEMOA) - XOF"),
                    ("ZAR", "Rand - ZAR (Afrique du Sud)"),
                    ("MAD", "Dirham - MAD (Maroc)"),
                    ("EGP", "Livre - EGP (Égypte)"),
                    ("NGN", "Naira - NGN (Nigéria)"),
                    ("EUR", "Euro - EUR"),
                    ("GBP", "Livre Sterling - GBP"),
                    ("CHF", "Franc Suisse - CHF"),
                    ("USD", "Dollar US - USD"),
                    ("CAD", "Dollar Canadien - CAD"),
                    ("BRL", "Real - BRL (Brésil)"),
                    ("MXN", "Peso - MXN (Mexique)"),
                    ("JPY", "Yen - JPY (Japon)"),
                    ("CNY", "Yuan - CNY (Chine)"),
                    ("INR", "Roupie - INR (Inde)"),
                    ("KRW", "Won - KRW (Corée du Sud)"),
                    ("THB", "Baht - THB (Thaïlande)"),
                    ("SGD", "Dollar - SGD (Singapour)"),
                    ("MYR", "Ringgit - MYR (Malaisie)"),
                    ("IDR", "Roupie - IDR (Indonésie)"),
                    ("PHP", "Peso - PHP (Philippines)"),
                    ("VND", "Dong - VND (Vietnam)"),
                    ("AED", "Dirham - AED (EAU)"),
                    ("SAR", "Riyal - SAR (Arabie Saoudite)"),
                    ("QAR", "Riyal - QAR (Qatar)"),
                    ("KWD", "Dinar - KWD (Koweït)"),
                    ("BHD", "Dinar - BHD (Bahreïn)"),
                    ("AUD", "Dollar Australien - AUD"),
                    ("NZD", "Dollar Néo-Zélandais - NZD"),
                ],
                default="XAF",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="benefice_attendu",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="cout_projet",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=15, null=True
            ),
        ),
    ]
