# Generated by Django 6.0.3 on 2026-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_projet_devise_benefice_projet_devise_cout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heureprojet",
            name="heure_debut",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heureprojet",
            name="heure_fin",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technician",
            name="taux_horaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Taux horaire en FCFA",
                max_digits=10,
                null=True,
            ),
        ),
    ]
