# Generated by Django 6.0.1 on 2026-03-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_ordretravail_objet_alter_ordretravail_mission"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordretravail",
            name="lieu",
            field=models.CharField(
                blank=True, help_text="Lieu de l'intervention", max_length=255
            ),
        ),
    ]
