# Generated by Django 6.0.3 on 2026-04-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_heureprojet_heure_debut_heureprojet_heure_fin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("depassement_heures", "Dépassement d'heures"),
                            ("depassement_delai", "Dépassement de délai"),
                            ("marge_critique", "Marge critique (<15%)"),
                            ("projet_termine", "Projet terminé"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("est_lue", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.projet",
                    ),
                ),
            ],
        ),
    ]
