# Generated by Django 6.0.1 on 2026-03-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_ordretravail_lieu"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.service",
            ),
        ),
    ]
