# Generated by Django 6.0.3 on 2026-04-24 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("en_cours", "En cours"),
                            ("resolu", "Résolu"),
                            ("ferme", "Fermé"),
                        ],
                        default="nouveau",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("moyenne", "Moyenne"),
                            ("haute", "Haute"),
                            ("critique", "Critique"),
                        ],
                        default="moyenne",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                ("date_fermeture", models.DateTimeField(blank=True, null=True)),
                (
                    "temps_passe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Temps passé en heures",
                        max_digits=6,
                    ),
                ),
                (
                    "solution",
                    models.TextField(blank=True, help_text="Solution apportée"),
                ),
                (
                    "commentaires",
                    models.TextField(blank=True, help_text="Commentaires internes"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="api.client",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technicien_assigne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_assigne",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TicketHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="api.ticket",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_action"],
            },
        ),
    ]
