# Generated by Django 6.0.1 on 2026-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_technician_service"),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournalier',
            name='service',
            field=models.CharField(choices=[('OSN', 'OSN'), ('OBT', 'OBT')], max_length=3, default='OSN'),
            preserve_default=False,
        ),
    ]