# Generated by Django 6.0.3 on 2026-04-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_ticket_tickethistorique"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="numero",
            field=models.IntegerField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="N° Ticket",
            ),
        ),
    ]
