# Generated by Django 6.0.3 on 2026-06-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_ticket_numero"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="commentaire",
            field=models.TextField(
                blank=True, help_text="Ex: Mission à Pointe-Noire du 22/06 au 12/07"
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="date_debut",
            field=models.DateField(
                blank=True, help_text="Début de la mission/congé", null=True
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="date_fin",
            field=models.DateField(
                blank=True, help_text="Fin de la mission/congé", null=True
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="statut_actuel",
            field=models.CharField(
                choices=[
                    ("disponible", "✅ Disponible"),
                    ("intervention", "🟠 En intervention"),
                    ("mission", "🟣 En mission"),
                    ("conges", "🔴 En congé"),
                ],
                default="disponible",
                help_text="Statut actuel du technicien (temps réel)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="technicien_assigne",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets_assigne",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AgendaTechnicien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("intervention", "En intervention"),
                            ("indisponible", "Indisponible"),
                            ("conges", "Congés"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda",
                        to="api.technician",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "heure_debut"],
                "unique_together": {("technicien", "date", "heure_debut")},
            },
        ),
    ]
