# Generated by Django 6.0.1 on 2026-03-22 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_add_duree_estimee_ot"),
        ("api", "0018_multi_techniciens"),
    ]

    operations = []
