# Generated by Django 6.0.1 on 2026-03-22 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_make_client_obligatoire"),
        ("api", "0022_back_to_single_tech"),
    ]

    operations = []
