# Generated by Django 6.0.1 on 2026-03-23 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_add_technicien_to_suivi_ot"),
        ("api", "0025_add_technicien_with_default"),
    ]

    operations = []
