# Generated by Django 6.0.1 on 2026-03-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_merge_20260323_1120"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rapportprojet",
            old_name="cadre",
            new_name="ingenieur",
        ),
        migrations.RenameField(
            model_name="rapportprojet",
            old_name="observations",
            new_name="remarques",
        ),
        migrations.RemoveField(
            model_name="rapportprojet",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="rapportprojet",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="technician",
            name="service",
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lignerapporthebdocadre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rapporthebdocadre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rapportprojetcadre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="suiviot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
